export { default as Table } from './Table.vue'
export { default as TableHead } from './TableHead.vue'
export { default as TableHeadRow } from './TableHeadRow.vue'
export { default as TableHeadCell } from './TableHeadCell.vue'
export { default as TableBody } from './TableBody.vue'
export { default as TableRow } from './TableRow.vue'
export { default as TableCell } from './TableCell.vue'
